@@ -1,22 +0,0 @@
# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
development:
  secret_key_base: 43615f101f9a8c1877601a85d3cfa4b52987d5558258d7645221b3470c309f2ac2110501aa0c243a4884f1198731cb9b0e0446a1d60bf3f4285448b6aa59ae41
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 186873c6a0595cdc2c72caee79bbbc99bb1d3c3a0613f5553598fb3b3ee98d01c11ed201986f7f2e1bcdd64fbe06a0e796d94928085ff70bd607b5d18859fb59
# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV[“AWS_ACCESS_KEY_ID”] %>
  aws_secret_access_key: <%= ENV[“AWS_SECRET_ACCESS_KEY”] %>